-- insert some test value


INSERT INTO account_user(name, email, username, password, comment_count) 
VALUES ('admin', 'admin@gmail.com', 'admin_username', 'admin_password', 2), 
       ('userOne', 'userOne@gmail.com', 'userOne_username', 'userOne_password', 2), 
       ('userTwo', 'userTwo@gmail.com', 'userTwo_username', 'userTwo_password',2);



INSERT INTO add_book(name, author, translator, year, genre, summary, cover)
VALUES('The Old Man and the Sea', 'Ernest Hemingway', '(Mohammad Taghi Faramarizi)', '1952', 'Literary,Fiction', 'Santiago is an aging, experienced fisherman who has gone eighty-four days without catching a fish. He is now seen as "salao" (colloquial pronunciation of "salado", which means salty), the worst form of unlucky. Manolin, a young man whom Santiago has trained since childhood, has been forced by his parents to work on a luckier boat. Manolin remains dedicated to Santiago, visiting his shack each night, hauling his fishing gear, preparing food, and talking about American baseball and Santiago s favorite player, Joe DiMaggio. Santiago says that tomorrow, he will venture far out into the Gulf Stream, north of Cuba in the Straits of Florida to fish, confident that his unlucky streak is near its end.', 'cover/The Old Man and the Sea.jpg'),
      ('Thus Spoke Zarathustra', 'Friedrich Nietzsche', '(Dariush Ashoori)', '1883', 'poetry, Novel, philosophical fiction', 'This book, which is Nietzsche s most important work, contains theories such as "superman", "death of God" and "eternal return" in their most complete form and most positive meaning. After ten years of seclusion in the Alps, Zarathustra feels that he wants to make people taste the nectar of his wisdom, so he descends to the city; But the people do not listen to the voice of inspiration, because they pay no attention to anything but clapping for a string player s tricks, and laugh at his words, which they do not understand. So Zoroaster should choose an apostle for himself who can address his "speech" which is contempt for the old ideals and is in the style of the old holy books such as the Avesta and the Bible. The first speech is an allegory entitled "Three Metamorphoses" in which one can understand how the human soul evolves, from obedience represented by the symbol of the camel to the extreme negation embodied by the symbol of the lion, and the sheer acknowledgment of which the child is its embodiment. . In the following speeches, a wide variety of topics are discussed: the author with the weak ego of low-income people who take refuge in the calm relaxation of morality; with metaphysics, which discredits the world by preaching abstraction; With the stagnancy of a cultural book that is too self-absorbed; with austerity that makes a person think of death; with the cult of government that suffocates people by turning them into impersonal machine slaves; And finally, he rises to fight with the vulgarity of thought. Other speeches, on the contrary, contain provocative affirmations: one praises war as a stimulus to human energy; The other sees the most beautiful form of friendship in the duality of personality, which is the fruit of solitude and reflection; The other puts the value of life, which has its own end, in front of single values; And finally, in the last speech, he teaches that abundant generosity, the healthy virtue that he likes to bestow on himself.', 'cover/Thus Spoke Zarathustra.jpg'),
      ('1984', 'George Orwell', '(Mehdi Saemi)', '1949', 'Dystopian, political fiction, social science fiction', 'In 1984, civilisation has been ravaged by world war, civil conflict, and revolution. Airstrip One (formerly known as Great Britain) is a province of Oceania, one of the three totalitarian super-states that rule the world. It is ruled by "The Party" under the ideology of "Ingsoc" (a Newspeak shortening of "English Socialism") and the mysterious leader Big Brother, who has an intense cult of personality. The Party brutally purges out anyone who does not fully conform to their regime, using the Thought Police and constant surveillance through telescreens (two-way televisions), cameras, and hidden microphones. Those who fall out of favour with the Party become "unpersons", disappearing with all evidence of their existence destroyed.', 'cover/1984.jpg');
      



INSERT INTO add_comment(comment, book_id, user_id, date) 
VALUES('Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus numquam assumenda hic aliquam vero sequi velit molestias .', '1', '1', current_date() ),
      ('Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus numquam assumenda hic aliquam vero sequi velit molestias .', '1', '3', current_date() ),
      ('Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus numquam assumenda hic aliquam vero sequi velit molestias .', '3', '1', current_date() ),
      ('Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus numquam assumenda hic aliquam vero sequi velit molestias .', '2', '2', current_date() ),
      ('Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus numquam assumenda hic aliquam vero sequi velit molestias .', '2', '3', current_date() ),
      ('Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus numquam assumenda hic aliquam vero sequi velit molestias .', '3', '2', current_date() );
